In [14]:
#Testing scraper for Twitchtracker
import urllib.request as urllib
from urllib.request import Request, urlopen
from bs4 import BeautifulSoup

import pandas as pd

#bypass 403 forbidden against web crawlers
req = Request('https://twitchtracker.com/statistics', headers={'User-Agent': 'Mozilla/5.0'})
html = urlopen(req).read()

soup = BeautifulSoup(html)

table = soup.find(id="big-one");
rows = table.find_all("tr");

df = pd.DataFrame(columns = ["Month", "Avg. Concur. Viewers", "Avg. Concur. Channels", "Time Watched", "Active Streamers"])

for row in rows:
    data = row.find_all("td");
    
    #Knowing the structure of the table, process all valid rows in standard order
    #Append each processed data item to our dataframe
    if len(data) != 0:
        month = data[0].get_text().strip()
        viewers = data[1].get_text().strip()
        channels = data[2].get_text().strip()
        watched = data[3].get_text().strip().split(" ")[0]
        streamers = data[4].get_text().strip()
#       If you want to see individual outputs
#         print("Date: " + month)
#         print("Viewers: " + viewers)
#         print("Channels: " + channels)
#         print("Time Watched: " + watched)
#         print("Streamers: " + streamers)
        data_dict = {"Month" : month, "Avg. Concur. Viewers": viewers, 
                     "Avg. Concur. Channels": channels, "Time Watched": watched, "Active Streamers": streamers}
        df = df.append(data_dict, ignore_index=True)
        
#Write our data and display the data
df.to_csv("totaltwitchdata.csv")
df

,Month,Avg. Concur. Viewers,Avg. Concur. Channels,Time Watched,Active Streamers
0,2012-09-01,77798,1986,55742267,n/a
1,2012-10-01,98835,2047,73302625,n/a
2,2012-11-01,109932,2205,78473126,n/a
3,2012-12-01,120537,2457,89458544,n/a
4,2013-01-01,147954,3016,109905163,n/a
...,...,...,...,...,...
88,2020-01-01,1357375,52821,1009887000,3935308
89,2020-02-01,1410516,53816,981719136,3753539
90,2020-03-01,1637064,65976,1217975616,5080031
91,2020-04-01,2486264,93618,1790110080,7213644
92,2020-05-01,2363201,100442,1645969497,n/a