In [15]:
#Aggregating Downloaded CSV Files for Twitch

import pandas as pd

#Masterdf holds all data
#Df is the dataframe to append
#Month is a string to track month
def dfprocess(masterdf, df, month):
    df = df.drop(df.columns[[0, 1, 13]], axis=1)
    df = df.set_index("Channel");
    df["Month"] = month;
    masterdf = masterdf.append(df);
    return masterdf;  

#Initialize our dataframe to the latest month
dfmaster = pd.read_csv("data/April2020.csv");
dfmaster = dfmaster.drop(dfmaster.columns[[0, 1, 13]], axis=1)
dfmaster = dfmaster.set_index("Channel");
dfmaster["Month"] = "4-2020";

csvarray = ["March2020.csv", "February2020.csv", "January2020.csv", "December2019.csv", 
            "November2019.csv", "October2019.csv", "September2019.csv", "August2019.csv", 
            "July2019.csv", "June2019.csv", "May2019.csv", "April2019.csv"];
montharray = ["2020-03-01", "2020-02-01", "2020-01-01", "2019-12-01", "2019-11-01", "2019-10-01", "2019-09-01", 
             "2019-08-01", "2019-07-01", "2019-06-01", "2019-05-01", "2019-04-01"]

for i in range(len(csvarray)):
    dftemp = pd.read_csv("data/" + csvarray[i])
    dfmaster = dfprocess(dfmaster, dftemp, montharray[i])
    
dfmaster = dfmaster.sort_values(by=["Channel", "Watch time"], ascending=[True, False]);

# Counts the occurances of a certain channel
channelcount = dfmaster.index.value_counts()

# Adds all channel names that appear less than 10 times in the dataset to the list "invalidchannels"
invalidchannels = []
mintimes = 10
for i in range(len(channelcount)):
    if channelcount[i] < mintimes:
        invalidchannels.append(channelcount.index[i])

#Drops all rows with the channel names in the list "invalidchannels" from the Dataframe 
for value in invalidchannels:
    dfmaster.drop(value, inplace=True)

indexes = dfmaster.index 

for value in dfmaster.index:
    first_val = value.find("(") + 1
    foreign_name = value
    if first_val != 0:
        second_val = value.find(")")
        foreign_name = value[first_val:second_val]
        x = value
    dfmaster = dfmaster.rename(index = {value : foreign_name})
    
    
counter = dfmaster.index.value_counts()
print("There are",counter.count(),"channels that appear at least",mintimes,"times in the dataset.")

    
dfmaster.to_csv("TotalChannelData.csv")                       
dfmaster

There are 46 channels that appear at least 10 times in the dataset.

,Watch time,Stream time,Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature,Language,Month
Channel,,,,,,,,,,,
AdmiralBahroo,145006575,15510,16796,9348,767646,3567,1260698,True,False,English,2020-03
AdmiralBahroo,133999260,15810,18081,8475,767646,8821,1401268,True,False,English,2019-07
AdmiralBahroo,113289465,13935,12942,8129,767646,2100,1091917,True,False,English,4-2020
AdmiralBahroo,107821695,11385,21053,9470,767646,24039,1664305,True,False,English,2019-09
AdmiralBahroo,94542885,12195,14637,7752,767646,4226,1094156,True,False,English,2020-01
...,...,...,...,...,...,...,...,...,...,...,...
hanryang1125,168360420,14985,23475,11234,476111,6552,2398051,True,True,Korean,2020-01
hanryang1125,167103915,15210,21727,10985,476111,9117,2505514,True,True,Korean,2019-08
hanryang1125,157870935,14955,20651,10555,476111,8961,2621446,True,True,Korean,2019-05
hanryang1125,154179660,12675,22027,12163,476111,7939,2468536,True,True,Korean,2019-04
hanryang1125,152302995,15150,18857,10052,476111,6044,2723455,True,True,Korean,2019-07